[ERROR] ME(1840044:281473857851424,MainProcess):2024-11-09-02:30:43.898.240 [mindspore/run_check/_check_version.py:388] CheckFailed: cannot import name 'utils' from partially initialized module 'tbe.common' (most likely due to a circular import) (/home/miniconda3/envs/ms2.2/lib/python3.8/site-packages/tbe/common/__init__.py)
[ERROR] ME(1840044:281473857851424,MainProcess):2024-11-09-02:30:43.898.537 [mindspore/run_check/_check_version.py:389] MindSpore relies on whl packages of "te" and "hccl" in the "latest" folder of the Ascend AI software package (Ascend Data Center Solution). Please check whether they are installed correctly or not, refer to the match info on: https://www.mindspore.cn/install
[WARNING] ME(1840995:281473857851424,GeneratorWorkerProcess):2024-11-09-02:31:09.490.147 [mindspore/dataset/engine/queue.py:121] Using shared memory queue, but rowsize is larger than allocated memory max_rowsize: 6.0MB, current rowsize: 114.9365234375MB.
[WARNING] ME(1840999:281473857851424,GeneratorWorkerProcess):2024-11-09-02:31:09.490.141 [mindspore/dataset/engine/queue.py:121] Using shared memory queue, but rowsize is larger than allocated memory max_rowsize: 6.0MB, current rowsize: 114.9365234375MB.
[WARNING] COMMON(1840044,ffffbd4f9020,python):2024-11-09-02:48:02.726.996 [mindspore/ccsrc/common/duplex_pipe.cc:111] Read] [DuplexPipe] Read was interrupted by system interrupt, retry: 0
[WARNING] MD(1840044,fffc38bff120,python):2024-11-09-02:56:27.836.351 [mindspore/ccsrc/minddata/dataset/engine/datasetops/source/generator_op.cc:231] operator()] Bad performance attention, it takes more than 25 seconds to generator.__next__ new row, which might cause `GetNext` timeout problem when sink_mode=True. You can increase the parameter num_parallel_workers in GeneratorDataset / optimize the efficiency of obtaining samples in the user-defined generator function.
[WARNING] MD(1840044,fffc33fff120,python):2024-11-09-02:56:27.837.438 [mindspore/ccsrc/minddata/dataset/engine/datasetops/data_queue_op.cc:1179] DetectPerBatchTime] Bad performance attention, it takes more than 25 seconds to fetch a batch of data from dataset pipeline, which might result `GetNext` timeout problem. You may test dataset processing performance(with creating dataset iterator) and optimize it.
epoch: 1 step: 5208, loss is 2.1261117458343506
Train epoch time: 4058282.103 ms, per step time: 779.240 ms
epoch: 2 step: 5208, loss is 2.1934659481048584
Train epoch time: 2512836.642 ms, per step time: 482.496 ms
epoch: 3 step: 5208, loss is 2.124619960784912
Train epoch time: 2562514.343 ms, per step time: 492.034 ms
epoch: 4 step: 5208, loss is 2.0248677730560303
Train epoch time: 2743472.235 ms, per step time: 526.780 ms
epoch: 5 step: 5208, loss is 2.1818037033081055
Train epoch time: 2526888.859 ms, per step time: 485.194 ms
epoch: 6 step: 5208, loss is 2.18389892578125
Train epoch time: 2522243.160 ms, per step time: 484.302 ms
epoch: 7 step: 5208, loss is 2.120333433151245
Train epoch time: 2548343.990 ms, per step time: 489.313 ms
epoch: 8 step: 5208, loss is 2.331974506378174
Train epoch time: 2509818.126 ms, per step time: 481.916 ms
epoch: 9 step: 5208, loss is 2.1982715129852295
Train epoch time: 2579430.282 ms, per step time: 495.282 ms
epoch: 10 step: 5208, loss is 2.0693020820617676
Train epoch time: 2495497.616 ms, per step time: 479.166 ms
